// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQYS_RZ-1hqQlNF-AUo_Ji9iGQmY5bePg',
    appId: '1:792333304002:web:3a86d33f55f46931b83b5b',
    messagingSenderId: '792333304002',
    projectId: 'pucminas-engsoftware-22',
    authDomain: 'pucminas-engsoftware-22.firebaseapp.com',
    storageBucket: 'pucminas-engsoftware-22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKsvVt2r_0KrtFdv0lzOflEch6WIfUUw',
    appId: '1:792333304002:android:181ebe8839e6f2c3b83b5b',
    messagingSenderId: '792333304002',
    projectId: 'pucminas-engsoftware-22',
    storageBucket: 'pucminas-engsoftware-22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLzppfEN-3oCaeLRWcGgsSXoI_qKKKEYM',
    appId: '1:792333304002:ios:42191e7a3119ef3cb83b5b',
    messagingSenderId: '792333304002',
    projectId: 'pucminas-engsoftware-22',
    storageBucket: 'pucminas-engsoftware-22.appspot.com',
    iosBundleId: 'com.example.projetointegradoPucminas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLzppfEN-3oCaeLRWcGgsSXoI_qKKKEYM',
    appId: '1:792333304002:ios:42191e7a3119ef3cb83b5b',
    messagingSenderId: '792333304002',
    projectId: 'pucminas-engsoftware-22',
    storageBucket: 'pucminas-engsoftware-22.appspot.com',
    iosBundleId: 'com.example.projetointegradoPucminas',
  );
}
